[server.pv.addon.broadcast]
broadcasting_specific = "Transmitiendo a %s"
broadcasting_wide = "Transmitiendo a %s-wide"

[server.pv.addon.broadcast.command]
world_set = "Establecer transmisi贸n con el modo mundo a %s"
world_usage = "Uso correcto: /vbroadcast world <world names>"
usage = "Uso: /vbroadcast <range|server|world> <range|world names>"
server_set = "Establecer transmisi贸n con el modo servidor"
range_set = "Establecer transmisi贸n con rango %d"
range_usage = "Uso: /vbroadcast range <number greater than 0>"
[client.pv.activation]
broadcast = "Transmisi贸n"
